use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :funk_and_schuster, FunkAndSchusterWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  static_url: [path: "http://localhost:8080"],
  watchers: [
    npm: ["run", "watch", cd: Path.expand("../assets", __DIR__)]
    # node: [
    #   "node_modules/webpack/bin/webpack.js",
    #   "--mode",
    #   "development",
    #   "--watch-stdin",
    #   cd: Path.expand("../assets", __DIR__)
    # ]
  ]

config :funk_and_schuster, :static_site,
  hostname: "http://localhost:4000",
  static_path: "./priv/static/",
  static_dirs: ~w(images icons css fonts),
  slugs: ~w(index about gallery contact process),
  output: "/home/tom/static-site/"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :funk_and_schuster, FunkAndSchusterWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/funk_and_schuster_web/views/.*(ex)$},
      ~r{lib/funk_and_schuster_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :funk_and_schuster, FunkAndSchuster.Repo,
  username: "postgres",
  password: "postgres",
  database: "funk_and_schuster_dev",
  hostname: "localhost",
  pool_size: 10

import_config "dev.secret.exs"
